# for postgres comment lines below in
# It is preferable to use postgres because this
# is what's used in production and it is necessary
# to work on the coldmap.
development: &development
  adapter: postgresql
  database: twinedb_development
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: twinedb_test
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: twinedb
  username: heatseekroot
  password: ENV['DATABASE_PASSWORD']
  host: localhost
  port: 5432
  pool: 10
